src/PMatches/PMatches.Frontend/Controllers/MatchesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PMatches.Domain.Entities;
using PMatches.Frontend.Data;
using PMatches.Frontend.Data.Entities;
using PMatches.Frontend.Models;
using PMatches.Frontend.Utils;
using PMatches.Persistence;

namespace PMatches.Frontend.Controllers
{
    public class MatchesController : Controller
    {
        private readonly DataContext _context;

        public MatchesController(DataContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string searchParam = "")
        {
            var matches = _context.Matches.Where(p => p.StatusId > 0);

            searchParam = searchParam.ToLower();
            var matchesList = matches.Where(m => m.EquipNameHome.ToLower().Contains(searchParam) || m.EquipNameVisitor.ToLower().Contains(searchParam)).ToList();

            return View(matchesList);
        }
         
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var entityM = await _context.Matches
                            .FirstOrDefaultAsync(m => m.Id == id);
            if (entityM == null)
            {
                return NotFound();
            }
            var modelE = EntityViewModelConverter.MatchEntityToViewModel(entityM);
            return View(modelE);
        }

        public IActionResult Create()
        {  
            return View();
        }
         
        // GET: Matches/Edit/5
        public async Task<IActionResult> Edit(int? identifier)
        {
            if (identifier == null)
            {
                return NotFound();
            }

            var entityM = await _context.Matches.FindAsync(identifier);
            if (entityM == null)
            {
                return NotFound();
            }
            var modelE = EntityViewModelConverter.MatchEntityToViewModel(entityM);

            return View(modelE);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Match entityM)
        {
            if (id != entityM.Id)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(entityM);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EntityExists(entityM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(entityM);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entityM = await _context.Matches
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entityM == null)
            {
                return NotFound();
            }

            return View(entityM);
        }

        // POST: Matches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var entityM = await _context.Matches.FindAsync(id);
            if (entityM != null)
            {
                _context.Matches.Remove(entityM);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool EntityExists(int id)
        {
            return _context.Matches.Any(e => e.Id == id);
        }



    }
}

src/PMatches/PMatches.Frontend/Controllers/StatusController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PMatches.Domain.Entities;
using PMatches.Frontend.Data;
using PMatches.Frontend.Data.Entities;
using PMatches.Persistence;

namespace PMatches.Frontend.Controllers
{
    public class StatusController : Controller
    {
        private readonly DataContext _context;

        public StatusController(DataContext context)
        {
            _context = context;
        }
         
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var vm = new StatusViewModel { Id = id.Value };

            return View(vm);
        }
         
        public IActionResult Create()
        {
            return View();
        }
         
        // GET: Matches/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entityM = await _context.Status.FindAsync(id);
            if (entityM == null)
            {
                return NotFound();
            }
            return View(entityM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Status entityM)
        {
            if (id != entityM.Id)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(entityM);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EntityExists(entityM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(entityM);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entityM = await _context.Status
                .FirstOrDefaultAsync(m => m.Id == id);
            if (entityM == null)
            {
                return NotFound();
            }

            return View(entityM);
        }

        // POST: Matches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var entityM = await _context.Status.FindAsync(id);
            if (entityM != null)
            {
                _context.Status.Remove(entityM);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        private bool EntityExists(int id)
        {
            return _context.Status.Any(e => e.Id == id);
        }
    }
}

src/PMatches/PMatches.Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PMatches.Frontend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PMatches.Frontend.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PMatches.Frontend</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a id="homeLink" class="nav-link text-dark my-nav-links my-nav-links-hacked" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a id="privacyLink" class="nav-link text-dark my-nav-links" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a id="privacyLink2" class="nav-link text-dark my-nav-links" href="Home/Privacy">Privacy 2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-controller="Matches" asp-action="Index"  > Matches</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-controller="Status" asp-action="Index"> Status</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container"> 
        <main role="main" class="pb-3"> 
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PMatches.Frontend - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>